//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public int ID { get; set; }
        public string Item_Name { get; set; }
        public Nullable<decimal> Item_Price { get; set; }
        public Nullable<int> Item_Amount { get; set; }
        public Nullable<int> Item_Supplier_ID { get; set; }
    
        public virtual Suppliers Suppliers { get; set; }
    }
}
